spring:
#  h2:
#    console:
#      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true;
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:tcp://localhost/~/fukufuku_spring;
#    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver